import {
  Battery,
  Smartphone,
  Camera,
  Monitor,
  Cpu,
  Shield,
  Wrench,
  Glasses,
  Square,
  Tag,
  Speaker,
  Power,
  Zap,
  Volume2,
  Wifi,
  Vibrate,
  SmartphoneIcon as Sim,
  Server,
  Thermometer,
  Radio,
  Package,
  Volume,
  Cable,
  CameraIcon as Sensor,
  Antenna,
  Eye,
  Phone,
  Headphones,
  Tablet,
  BoxIcon as Button,
  PenToolIcon as Tool,
  Tv,
  TouchpadIcon as TouchScreen,
  Plug,
  PinIcon as Chip,
  Home,
  Sticker,
  Bell,
  Fingerprint,
  CircuitBoard,
  BatteryCharging,
} from "lucide-react"

// Mapeo de categorías a iconos
export const categoryIcons = {
  Baterías: Battery,
  Tapas: Square,
  Camaras: Camera,
  Modulos: Monitor,
  Placas: Cpu,
  Blindajes: Shield,
  Tornillos: Wrench,
  Chasis: Smartphone,
  Glass: Glasses,
  Marco: Square,
  "Tag on": Tag,
  Parlante: Speaker,
  "Power Flex": Power,
  "Flash Flex": Zap,
  "Volumen Flex": Volume2,
  "Flex Wifi": Wifi,
  Vibrador: Vibrate,
  "Porta Sim": Sim,
  "Socalo de Sim": Server,
  Sensores: Thermometer,
  Antenas: Radio,
  Combos: Package,
  Speaker: Volume,
  "Flex de Carga": Cable,
  "Flex de Sensor": Sensor,
  "Flex Antena": Antenna,
  "Visor de Camara": Eye,
  Celular: Phone,
  Accesorios: Headphones,
  Tablet: Tablet,
  Botones: Button,
  "Herramientas e insumos": Tool,
  Tv: Tv,
  Tactil: TouchScreen,
  "Pines de Carga": Plug,
  "Ic de Carga": Chip,
  "Home Flex": Home,
  Pegatinas: Sticker,
  Buzzer: Bell,
  "Home boton": Button,
  "Sensor Huella": Fingerprint,
  "Flex home": Home,
  "Main Flex": CircuitBoard,
  "Placa de Carga": BatteryCharging,
}

// Función para obtener el icono de una categoría
export function getCategoryIcon(categoryName: string) {
  return categoryIcons[categoryName as keyof typeof categoryIcons] || Package
}
